#ifndef COMMON_H
#define COMMON_H

#define STATUS_SUCCESS 0
#define STATUS_ERROR -1
#define STATUS_FILE_ERROR 1
#define STATUS_NOT_IMPLEMENTED 8

// HTTP and network statuses
#define STATUS_NETWORK_ERROR 2
#define STATUS_NETWORK_CLIENT_ERROR 3
#define STATUS_NETWORK_AUTHENTICATION_ERROR 4
#define STATUS_NETWORK_SERVER_ERROR 5
#define STATUS_NETWORK_NOT_FOUND_ERROR 6
#define STATUS_BAD_HTTP_CODE 7

#endif
