#ifndef COMMON_H
#define COMMON_H

#define STATUS_SUCCESS 0
#define STATUS_ERROR -1
#define STATUS_FILE_ERROR 1

// Http and network
#define STATUS_NETWORK_ERROR 2
#define STATUS_NETWORK_CLIENT_ERROR 3
#define STATUS_AUTHENTICATION_ERROR 4
#define STATUS_NETWORK_SERVER_ERROR 5
#define STATUS_BAD_HTTP_CODE 6

#endif

