#ifndef COMMON_H
#define COMMON_H

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_ERROR = -1,
    STATUS_FILE_ERROR = 1,
    STATUS_NOT_IMPLEMENTED = 8,
    // HTTP and network statuses
    STATUS_NETWORK_ERROR = 2,
    STATUS_NETWORK_CLIENT_ERROR = 3,
    STATUS_NETWORK_AUTHENTICATION_ERROR = 4,
    STATUS_NETWORK_SERVER_ERROR = 5,
    STATUS_NETWORK_NOT_FOUND_ERROR = 6,
    STATUS_BAD_HTTP_CODE = 7
} status_code;

#endif
