#include "common.h"
#include "github_api.h"
#include "network.h"
#include "spotify_api.h"
#include <curl/curl.h>
#include <getopt.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define FILE_CONTENT_INITIAL_SIZE 1000
#define TIME_STRING_MAX_SIZE 128

status_code append_string(const char *input, char *content, int current_size, int current_pos, int *new_pos_out, int *new_size_out,
                  char **content_out) {
    int input_len = strlen(input);
    int new_size = current_size;
    // -1 to overwrite old null terminator
    int print_pos = (current_pos == 0) ? 0 : current_pos - 1;
    // where null terminator will be after this write
    int new_pos = print_pos + input_len + 1;

    if (new_pos > current_size) {
        new_size += FILE_CONTENT_INITIAL_SIZE;

        char *tmp = realloc(content, new_size);
        if (!tmp)
            return STATUS_ERROR;

        content = tmp;
    }

    snprintf(content + print_pos, new_size - print_pos, "%s", input);

    *new_pos_out = new_pos;
    *new_size_out = new_size;
    *content_out = content;

    return STATUS_SUCCESS;
}

status_code format_artist_stats(char *content, int current_size, int pos, artist *artists, int artists_len, int *new_size_out,
                        int *pos_out) {
    if (append_string("## Top Artists\n", content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS)
        return STATUS_ERROR;

    for (int i = 0; i < artists_len; i++) {
        char *row;
        asprintf(&row, "%d. **%s**\n", i + 1, artists[i].name);

        int write_status = append_string(row, content, current_size, pos, &pos, &current_size, &content);
        free(row);

        if (write_status != STATUS_SUCCESS)
            return STATUS_ERROR;
    }

    *new_size_out = current_size;
    *pos_out = pos;

    return STATUS_SUCCESS;
}

status_code format_song_stats(char *content, int current_size, int pos, song *songs, int songs_len, int *new_size_out,
                      int *pos_out) {
    if (append_string("\n## Top Tracks\n", content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS)
        return STATUS_ERROR;

    for (int i = 0; i < songs_len; i++) {
        char *row;
        if (asprintf(&row, "%d. **%s** · %s\n", i + 1, songs[i].name, songs[i].artist) == -1)
            return STATUS_ERROR;

        int write_state = append_string(row, content, current_size, pos, &pos, &current_size, &content);
        free(row);

        if (write_state != STATUS_SUCCESS)
            return STATUS_ERROR;
    }

    *new_size_out = current_size;
    *pos_out = pos;

    return STATUS_SUCCESS;
}

status_code get_current_datetime(char **current_time_out) {
    char *formatted_time = NULL;
    int return_value = STATUS_ERROR;

    time_t tmp_time;
    if (time(&tmp_time) == -1) {
        perror("time");
        goto cleanup;
    }

    struct tm *current_time = localtime(&tmp_time);
    if (!current_time) {
        perror("localtime");
        goto cleanup;
    }

    formatted_time = malloc(TIME_STRING_MAX_SIZE);
    if (!formatted_time) {
        perror("malloc");
        goto cleanup;
    }

    if (strftime(formatted_time, TIME_STRING_MAX_SIZE, "%Y-%m-%d %H:%M:%S", current_time) == 0) {
        fprintf(stderr, "strftime: result is larger than buffer, formatting failed\n");
        goto cleanup;
    }

    *current_time_out = formatted_time;
    formatted_time = NULL;

    return_value = STATUS_SUCCESS;

cleanup:
    free(formatted_time);
    return return_value;
}

status_code format_file(artist *artists, int artists_len, song *songs, int songs_len, char **file_content_out) {
    char *content = NULL;
    char *current_time = NULL;
    int current_size = FILE_CONTENT_INITIAL_SIZE;
    int pos = 0;
    status_code return_value = STATUS_ERROR;

    content = malloc(current_size);
    if (!content) {
        perror("malloc");
        goto cleanup;
    }

    if (append_string("# Current Spotify Favorites\n\n", content, current_size, pos, &pos, &current_size, &content) !=
        STATUS_SUCCESS)
        goto cleanup;

    if (get_current_datetime(&current_time) != STATUS_SUCCESS)
        goto cleanup;

    if (append_string("*Generated by [Spotify Tracker](https://github.com/ViggoValfridsson/spotify_tracker) using data "
                      "from Spotify Web API.*\n\n",
                      content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS)
        goto cleanup;

    if (format_artist_stats(content, current_size, pos, artists, artists_len, &current_size, &pos))
        goto cleanup;

    if (format_song_stats(content, current_size, pos, songs, songs_len, &current_size, &pos))
        goto cleanup;

    if (append_string("\n*Data last updated at ", content, current_size, pos, &pos, &current_size, &content) !=
        STATUS_SUCCESS)
        goto cleanup;

    if (append_string(current_time, content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS)
        goto cleanup;

    if (append_string("*", content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS)
        goto cleanup;

    *file_content_out = content;
    content = NULL;

    return_value = STATUS_SUCCESS;

cleanup:
    free(content);
    free(current_time);

    return return_value;
}

status_code post_artists_to_github() {
    access_token *token = NULL;
    artist *artists = NULL;
    song *songs = NULL;
    char *file_content = NULL;

    status_code return_value = refresh_access_token(&token);
    if (return_value != STATUS_SUCCESS)
        goto cleanup;

    int artists_len;
    return_value = get_top_artists(token, &artists, &artists_len);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to fetch top artists\n");
        goto cleanup;
    }

    int songs_len;
    return_value = get_top_songs(token, &songs, &songs_len);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to fetch top songs\n");
        goto cleanup;
    }

    return_value = format_file(artists, artists_len, songs, songs_len, &file_content);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to format file\n");
        goto cleanup;
    }

    return_value = update_repo_file_content(file_content);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to update repository file\n");
        goto cleanup;
    }

    printf("Successfully updated Spotify stats\n");

cleanup:
    free(token);
    free(artists);
    free(songs);
    free(file_content);

    return return_value;
}

int main(int argc, char *argv[]) {
    int return_value = STATUS_ERROR;
    bool is_logging_in = false;

    CURLcode res = curl_global_init(CURL_GLOBAL_ALL);
    if (res) {
        fprintf(stderr, "Failed to initialize curl\n");
        return res;
    }

    int opt;
    static struct option long_options[] = {{"login", no_argument, 0, 'l'}, {0, 0, 0, 0}};
    while ((opt = getopt_long(argc, argv, "l", long_options, NULL)) != -1) {
        switch (opt) {
        case 'l':
            is_logging_in = true;
            break;
        }
    }

    if (is_logging_in)
        return_value = login();
    else
        return_value = post_artists_to_github();

    curl_global_cleanup();
    return return_value;
}
