#include "common.h"
#include "network.h"
#include "spotify_api.h"
#include <curl/curl.h>
#include <getopt.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define GIST_INITIAL_SIZE 1000

int add_string_to_gist(char *input, char *content, int current_size, int current_pos, int *new_pos_out,
                       int *new_size_out, char **content_out) {
    int input_len = strlen(input);
    int new_size = current_size;
    // -1 to overwrite old null terminator
    int print_pos = (current_pos == 0) ? 0 : current_pos - 1;
    // where null terminator will be after this write
    int new_pos = print_pos + input_len + 1;

    if (new_pos > current_size) {
        new_size += GIST_INITIAL_SIZE;

        char *tmp = realloc(content, new_size);
        if (!tmp) {
            return STATUS_ERROR;
        }

        content = tmp;
    }

    snprintf(content + print_pos, new_size - print_pos, "%s", input);

    *new_pos_out = new_pos;
    *new_size_out = new_size;
    *content_out = content;

    return STATUS_SUCCESS;
}

int format_gist(artist *artists, int artist_len, song *songs, int song_len, char **gist_out) {
    char *content = NULL;
    int current_size = GIST_INITIAL_SIZE;
    int pos = 0;

    content = malloc(current_size);

    char main_header[] = "# Current Spotify Favorites\n\n";
    if (add_string_to_gist(main_header, content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS) {
        free(content);
        return STATUS_ERROR;
    }

    char app_info[] = "*Generated by [Spotify Tracker](https://github.com/ViggoValfridsson/spotify_tracker) using data "
                      "from Spotify Web API*\n\n";
    if (add_string_to_gist(app_info, content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS) {
        free(content);
        return STATUS_ERROR;
    }

    char artist_header[] = "## Top Artists\n";
    if (add_string_to_gist(artist_header, content, current_size, pos, &pos, &current_size, &content) !=
        STATUS_SUCCESS) {
        free(content);
        return STATUS_ERROR;
    }

    for (int i = 0; i < artist_len; i++) {
        char *row;
        asprintf(&row, "%d. **%s**\n", i + 1, artists[i].name);

        int write_status = add_string_to_gist(row, content, current_size, pos, &pos, &current_size, &content);
        free(row);
        if (write_status != STATUS_SUCCESS) {
            free(content);
            return STATUS_ERROR;
        }
    }

    char song_header[] = "\n## Top Tracks\n";
    if (add_string_to_gist(song_header, content, current_size, pos, &pos, &current_size, &content) != STATUS_SUCCESS) {
        free(content);
        return STATUS_ERROR;
    }

    for (int i = 0; i < song_len; i++) {
        char *row;
        asprintf(&row, "%d. **%s** · %s\n", i + 1, songs[i].name, songs[i].artist);

        int write_state = add_string_to_gist(row, content, current_size, pos, &pos, &current_size, &content);
        free(row);
        if (write_state != STATUS_SUCCESS) {
            free(content);
            return STATUS_ERROR;
        }
    }

    *gist_out = content;
    return STATUS_SUCCESS;
}

int post_artists_to_gist() {
    access_token *token = NULL;
    artist *artists = NULL;
    int artists_len;
    song *songs = NULL;
    int songs_len;
    char *gist = NULL;

    int return_value = refresh_access_token(&token);
    if (return_value != STATUS_SUCCESS) {
        goto cleanup;
    }

    return_value = get_top_artists(token, &artists, &artists_len);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to fetch top artists\n");
        goto cleanup;
    }

    return_value = get_top_songs(token, &songs, &songs_len);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to fetch top songs\n");
        goto cleanup;
    }

    return_value = format_gist(artists, artists_len, songs, songs_len, &gist);
    if (return_value != STATUS_SUCCESS) {
        fprintf(stderr, "Failed to format gist\n");
        goto cleanup;
    }

    printf("%s", gist);

cleanup:
    free(token);
    free(artists);
    free(songs);
    free(gist);

    return return_value;
}

int main(int argc, char *argv[]) {
    CURLcode res = curl_global_init(CURL_GLOBAL_ALL);

    if (res) {
        return res;
    }

    static struct option long_options[] = {{"login", no_argument, 0, 'l'}, {0, 0, 0, 0}};
    int opt;
    int return_value = STATUS_ERROR;
    bool is_logging_in = false;

    while ((opt = getopt_long(argc, argv, "l", long_options, NULL)) != -1) {
        switch (opt) {
        case 'l':
            is_logging_in = true;
            break;
        }
    }

    if (is_logging_in) {
        return_value = login();
    } else {
        return_value = post_artists_to_gist();
    }

    curl_global_cleanup();
    return return_value;
}
